#! /bin/sh
CB="#ff272822"
C0="#ff000000"
C1="#fff92672"
C2="#ffa6e22e"
C3="#ffe6db74"
C4="#ff66d9ef"
C5="#ffae81ff"
C6="#ff00d9d9"
C7="#fff5deb3"
C8="#ff555555"
C9="#ffdd4278"

BSPCf="bspc desktop -f "

while read -r line ; do
    case $line in
        S*)
            # clock output
            clock="%{F$C6}%{F$C0}%{U$C6}%{B$C6} %{A:~/.scripts/toggle_conky cal:}${line#?}%{A}"
            ;;
        T*)
            # xtitle output
            title="%{B-}%{F$C7}${line#?}"
            ;;
        Z*)
            # Now Playing
            now_playing="%{U$C6}%{B$C6}%{F$C0}%{A:~/.scripts/panel/now_playing_click:}${line#?}%{A}"
            ;;
        A*)
            # Teamspeak Server
            ts="%{F$C8}⮁%{F$C0} %{A:~/.scripts/toggle_conky ts:}${line#?}%{A} %{F$C6}%{B-}%{U-}"
            ;;
        L*)
            # System Load
            system_load="${line#?}"
            ;;
        M*)
          # Memory Usage
          memory="⭦${line#?} %{F$C8}⮃%{F$C0}"
          ;;
        N*)
          # Network IPs
          network="${line#?} %{F$C8}⮃%{F$C0}"
          ;;
        C*)
          # CPU Usage
          cpu="⭥${line#?} %{F$C8}⮃%{F$C0}"
          ;;
        E*)
            temperature="%{F$C4}%{F$C0}%{U$C4}%{B$C4} ${line#?} %{F$C8}⮃%{F$C0}"
          ;;
        W*)
            # bspwm internal state
            screen="l"
            wm_info_left=""
            wm_info_right=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                wm_infos=""
                case $item in
                    O*)
                        # focused occupied desktop
                        wm_infos=" %{B-F-U$C2+u}${name}%{-uU-}"
                        ;;
                    F*)
                        # focused free desktop
                        wm_infos=" %{B-F$C8U$C2+u}${name}%{-uU-}"
                        ;;
                    U*)
                        # focused urgent desktop
                        wm_infos=" %{B$C1F-U$C2+u}${name}%{-uU-}"
                        ;;
                    o*)
                        # occupied desktop
                        wm_infos=" %{B-}%{F-}%{A:${BSPCf}${name}:}${name}%{A}"
                        ;;
                    f*)
                        # free desktop
                        wm_infos=" %{B-}%{F$C8}%{A:${BSPCf}${name}:}${name}%{A}%{F-}"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos=" %{B$C1}%{F-}${name}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_info_right="$wm_info_right  %{B-}%{F$C6}$layout"
                        ;;
                    *HDMI2*)
                        # Left monitor
                        screen="l"
                        ;;
                    *HDMI3*)
                        # Right monitor
                        screen="r"
                        ;;
                esac
                shift

                case $screen in
                  l)
                    wm_info_left="$wm_info_left$wm_infos"
                    ;;
                  r)
                    wm_info_right="$wm_info_right $wm_infos"
                    ;;
                esac
            done
            ;;
    esac

    right_right="$temperature $network $cpu $memory $system_load $clock "
    left_left="%{B$C6} $now_playing $ts"
    left_centre="%{F$C0}0%{F$C1}1%{F$C2}2%{F$C3}3%{F$C4}4%{F$C5}5%{F$C6}6%{F$C7}7%{F$C8}8%{F$C9}9%{F-}"
    left_right=" $wm_info_left "

    printf "%s\n" \
      "%{S0}$left_left%{r}$left_right%{S2}%{l}$wm_info_right $right_left%{c}$title%{r}$right_right%{U-F-B-}"

    #printf "%s\n" \
      #"\\l$wm_info_right $right_left\\c$title\\r$right_right\\sn\\l\\f2$left_left\\c$left_centre\\r$left_right\\ab \\aca\\ae"
      #"$wm_info_right $right_left " \
      #"$title " \
      #"$system_load $clock " \
      #"$now_playing " \
      #"" \
      #"$wm_info_left "
done
