#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_FONT="-misc-ohsnap.icons-medium-r-normal--14-101-100-100-c-70-iso8859-1"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a, %B %d @ %H:%M' > "$PANEL_FIFO" &
~/scripts/panel/now_playing > "$PANEL_FIFO" &
~/scripts/panel/load > "$PANEL_FIFO" &
~/scripts/panel/temperature > "$PANEL_FIFO" &
~/scripts/panel/cpu > "$PANEL_FIFO" &
~/scripts/panel/memory > "$PANEL_FIFO" &
~/scripts/panel/if > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | panel_bar | bar &
        ;;
    dzen2)
        . panel_colors
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "$PANEL_FONT" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
        ;;
esac

wait
