#! /bin/sh

echo "bspwm autostart" >> /home/lightstalker/startup.log

xrdb ~/.Xresources
start-pulseaudio-x11 &
wmname BSPWM
urxvtd &
synergys &
~/scripts/autostart_apps &
# compton --config ~/.compton.conf --paint-on-overlay &
cairo-compmgr &

# Background image
hsetroot -fill "/home/lightstalker/Pictures/wallpaper.jpg" &
