#!/bin/sh

################################################################################
# bar script                                                                   #
# Network interface display                                                    #
#                                                                              #
# Displays either the current internal/external IP address or the loopback     #
# IP. Currently will always try to reach out for an external IP (needs to      #
# change). Cannot handle more than one internal IP.                            #
#                                                                              #
# Refresh rate: 1 minute                                                       #
################################################################################

while true ; do
  internal=`ifconfig | grep "inet" | grep -v "inet6" | awk 'BEGIN{loopback="";actual=""}{c=split($0,a,"(\\\\:|\\\\s)+");if(match(a[3],"^127.") || match(a[3], "^172.")){loopback=a[3]}else{actual=a[3]}}END{if(actual==""){print loopback}else{print actual}}'`
  external=`curl -s icanhazip.com`
  echo "N$internal / $external"
  sleep 60
done
