#!/bin/sh

TEMPFILE="$HOME/.tmp/output.png"
file="$1"

convert -resize 1920x1080\< "$file" $TEMPFILE
montage $TEMPFILE $TEMPFILE -tile 1x2 -geometry 1920x1080\< ~/Pictures/wallpaper.png
rm $TEMPFILE

hsetroot -fill ~/Pictures/wallpaper.png
