#!/bin/bash

# Taken from:
# https://github.com/u-ra/dotfiles/blob/master/.config/bspwm/panel/scripts/toggle_conky

if [ $(pgrep -cf conky_$1) -gt 0 ]; then
        if [ "$(xdotool search --onlyvisible --class conky_$1)" != "" ]; then
                xdotool search --class conky windowunmap %@
        else
                xdotool search --class conky windowunmap %@
                xdotool search --class conky_$1 windowmap %1 windowraise
        fi
else
        xdotool search --class conky windowunmap %@
        conky -c ~/.scripts/panel/conky/conky_$1
fi
